#57 IdentifierTypeCode Binding Change
HL7Austria/HL7-AT-FHIR-Core-R4 pull request #68
Opened 2023-02-12 14:25 UTC by regelkraut

Changed the binding of identifier.type to the new ELGA ValueSet for identifierTypeCodes

Closes #57

2023-02-21 05:54 UTC, Nik-xT requested changes
Renaming the ValueSet came from the last discussion in TC Terminology. ValueSet is already deleted with its old name and published with its new one.

2023-02-21 05:54 UTC, Nik-xT commented on input/fsh/at-core-patient.fsh
> +* identifier.type from https://termgit.elga.gv.at/ValueSet/elga-patientidentifier (extensible)
ValueSet was renamed, please change to
```suggestion
* identifier.type from https://termgit.elga.gv.at/ValueSet/hl7-at-patientidentifier (extensible)
```

2023-02-21 05:54 UTC, Nik-xT commented on input/fsh/at-core-patient.fsh
> +* identifier[socialSecurityNumber].type from https://termgit.elga.gv.at/ValueSet/elga-patientidentifier (extensible)
ValueSet was renamed, please change to
```suggestion
* identifier[socialSecurityNumber].type from https://termgit.elga.gv.at/ValueSet/hl7-at-patientidentifier (extensible)
```

2023-02-21 05:54 UTC, Nik-xT commented on input/fsh/at-core-patient.fsh
> +* identifier[bPK].type from https://termgit.elga.gv.at/ValueSet/elga-patientidentifier (extensible)
ValueSet was renamed, please change to
```suggestion
* identifier[bPK].type from https://termgit.elga.gv.at/ValueSet/hl7-at-patientidentifier (extensible)
```

2023-02-21 05:54 UTC, Nik-xT commented on input/fsh/at-core-patient.fsh
> +* identifier[localPatientId].type from https://termgit.elga.gv.at/ValueSet/elga-patientidentifier (extensible)
ValueSet was renamed, please change to
```suggestion
* identifier[localPatientId].type from https://termgit.elga.gv.at/ValueSet/hl7-at-patientidentifier (extensible)
```

2023-02-27 12:32 UTC, Nik-xT approved these changes
Looking good!
The first step of getting valuesets & codesystems out of the IG to a TX like termgit.

2023-03-06 15:19 UTC, Nik-xT approved these changes

2023-03-06 15:22 UTC, regelkraut commented
@Nik-xT  I had to adapt the binding once more, but only on the level of the actual slices.
For some reason, in order to be applied by Sushi, I had to strengthen the binding from "extensible" to "required" (but just on the slice level). Hope that change is still ok for you as reviewer.

2023-03-06 16:05 UTC, aschuler84 commented
> @Nik-xT I had to adapt the binding once more, but only on the level of the actual slices. For some reason, in order to be applied by Sushi, I had to strengthen the binding from "extensible" to "required" (but just on the slice level). Hope that change is still ok for you as reviewer.

@regelkraut IMHO this makes sense, otherwise it would be possible to have codes not available in the binded valueset which would make discrimination of the slice type impossible. Seems as if sushi verifies this, not sure though?

2023-03-06 16:27 UTC, aschuler84 approved these changes
Looking good from my side, no further changes.

2023-03-06 16:28 UTC, merged